[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pyAMaFiL"
version = "0.0.1"
dependencies = [
    "numpy",
    "scipy",
    "sunpy",
    'importlib-metadata; python_version>="3.10"',
]